ka/ka/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$','blog.views.index'),
    url(r'^(?P<slug>[\w\-]+)/$', 'blog.views.post'),
    url(r'^p/(?P<slug>[\w\-]+)/$', 'blog.views.page'),
    url(r'^add_comment/(?P<slug>[\w\-]+)/$', 'blog.views.add_comment'),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
           ) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ka/blog/models.py
from django.db import models
from django.core.urlresolvers import reverse
from redactor.fields import RedactorField
from django.contrib.auth.models import User
from django.utils.html import strip_tags

class Stock(models.Model):
    company = models.CharField(max_length=255, unique=True)
    symbol = models.CharField(max_length=10, unique=True)
    
    class Meta:
        ordering = ['company']
    
    def __str__(self):
        return self.company

class Page(models.Model):
    title = models.CharField(max_length=255, unique=True)
    subtitle = models.CharField(max_length=255, null=True, blank=True)
    slug = models.SlugField(max_length=255, unique=True)
    order = models.IntegerField(unique=True)
    content = RedactorField(verbose_name=u'Text')
    published = models.BooleanField(default=True)
    
    class Meta:
        ordering = ['order']
    
    def get_absolute_url(self):
        return reverse('blog.views.page',args=[self.slug])
    
    def __unicode__(self):
        return u'%s' % self.title

class Tag(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        ordering = ['name']
    
    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True,
                            max_length=255)
    description = models.CharField(max_length=255, null=True, blank=True,help_text="Leave blank for auto-fill")
    author = models.ForeignKey(User, null=True, blank=True,editable=False)
    content = RedactorField(verbose_name=u'Text')
    published = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    tag = models.ManyToManyField(Tag, related_name="posts", related_query_name="post", blank=True)
    stock = models.ManyToManyField(Stock,related_name="posts",related_query_name="post", blank=True)
    imageURL = models.URLField(max_length=255, null=True, blank=True,help_text="Aim for 900x300 resolution")
    
    class Meta:
        ordering = ['-created']
    
    def __unicode__(self):
        return u'%s' % self.title
    
    def get_absolute_url(self):
        return reverse('blog.views.post',args=[self.slug])
    
    def get_comment_url(self):
        return reverse('blog.views.add_comment',args=[self.slug])
    
    def save(self, *args, **kwargs):
        if self.content and (self.description is None or self.description == ""):
            suffix = "..."
            length = 100
            content = strip_tags(self.content)
            self.description = content if len(content) <= length else content[:length-len(suffix)].rsplit(' ', 1)[0] + suffix
        super(Post, self).save(*args, **kwargs)
        
class Comment(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=60)
    author_ip = models.GenericIPAddressField(null=True,blank=True)
    body = models.TextField()
    post = models.ForeignKey(Post)
    validated = models.BooleanField(default=False)
    admin = models.BooleanField(default=False)

    def __unicode__(self):
        return unicode(self.body[:60])
    
    class Meta:
        ordering = ['-created']

ka/blog/forms.py
from django import forms
from django.forms import ModelForm
from blog.models import Comment

class CommentForm(ModelForm):
    author = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    body = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control','rows':3}))
    class Meta:
        model = Comment
        exclude = ["post"]

ka/blog/views.py
import math
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.context_processors import csrf
from django.contrib import messages
from blog.models import Post
from blog.models import Tag
from blog.models import Stock
from blog.models import Page
from blog.models import Comment
from blog.forms import CommentForm
from blog.utils import *
from ipware.ip import get_ip

def index(request):
    #Filter by tags and queries
    queryParam = request.GET.get('q')
    tagParam = request.GET.get('tag')
    if tagParam:
        post_list = Post.objects.filter(published=True, tag__slug=tagParam)
    elif queryParam:
        postQuery = get_query(queryParam, ['title', 'content','description','tag__name','stock__symbol','stock__company'])
        post_list = Post.objects.filter(postQuery,published=True).distinct()
    else:
        post_list = Post.objects.filter(published=True)
    paginator = Paginator(post_list,3) # Show 3 posts per page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        #If page is not an integer, deliver first page.
        posts = paginator.page(1)
    except EmptyPage:
        #If page is out of range, deliver last page of results
        posts = paginator.page(paginator.num_pages)
    #Tags
    tags = Tag.objects.all()
    half_tags = math.ceil(len(tags)/2.0)
    #Relevant stocks
    stockLen = 0
    for post in posts:
            post.stocks = Stock.objects.filter(post__slug=post.slug)
            stockLen += len(post.stocks)
    #find all published pages
    pages = Page.objects.filter(published=True)
    #now return the rendered template
    return render(request,'blog/index.html',{'posts':posts,'tags':tags,'half_tags':half_tags,'tagParam':tagParam,'queryParam':queryParam,'stockLen':stockLen,'pages':pages})

def post(request,slug):
    #get the Post object
    post = get_object_or_404(Post,slug=slug)
    #Tags
    tags = Tag.objects.filter(post__slug=post.slug)
    half_tags = math.ceil(len(tags)/2.0)
    #Stocks
    post.stocks = Stock.objects.filter(post__slug=post.slug)
    stockLen = len(post.stocks)
    #Comments
    comments = Comment.objects.filter(post=post,validated=True)
    #find all published pages
    pages = Page.objects.filter(published=True)
    #now return the rendered template
    return render(request,'blog/post.html',{'post':post,'tags':tags,'half_tags':half_tags,'stockLen':stockLen,'pages':pages,'comments':comments,'form':CommentForm()})

def page(request,slug):
    page = get_object_or_404(Page,slug=slug)
    #find all published pages
    pages = Page.objects.filter(published=True)
    #Tags
    tags = Tag.objects.all()
    half_tags = math.ceil(len(tags)/2.0)
    return render(request,'blog/page.html',{'page':page,'pages':pages,'tags':tags,'half_tags':half_tags,'pages':pages})

def add_comment(request, slug):
    """Add a new comment."""
    p = request.POST
    post = Post.objects.get(slug=slug)
    author_ip = get_ip(request)

    if p.has_key("body") and p["body"]:
        author = "Anonymous"
        if p["author"]: author = p["author"]

        comment = Comment(post=post)
        cf = CommentForm(p, instance=comment)
        cf.fields["author"].required = False

        comment = cf.save(commit=False)
        comment.author = author
        comment.author_ip = author_ip
        comment.save()
        messages.success(request,'Thank you for submitting a comment. It will appear once reviewed by an administrator.')
    else:
        messages.error(request, 'Something went wrong. Please try again later.')
    return HttpResponseRedirect(post.get_absolute_url())

ka/ka/templates/blog/base.html
<!DOCTYPE html>
    <html>
        <head>
            <title>
                {% block title %}{% endblock %}
            </title>
            
            <meta charset="utf-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <meta name="description" content="">
            <meta name="author" content="">
            
            {% load staticfiles %}
            {% load compress %}
            
            <link rel="shortcut icon" type="image/png" href="{% static "blog/favicon.ico" %}"/>
        
            {% compress css %}
            <!-- Bootstrap Core CSS -->
            <link href="{% static "blog/css/bootstrap.min.css" %}" rel="stylesheet">
            <!-- Bootstrap Core CSS -->
            <link href="{% static "blog/css/font-awesome.min.css" %}" rel="stylesheet">
            <!-- Custom CSS -->
            <link href="{% static "blog/css/blog-home.css" %}" rel="stylesheet">
            <link href="{% static "blog/css/blog-post.css" %}" rel="stylesheet">
            <link href="{% static "blog/css/additional.css" %}" rel="stylesheet">
            {% endcompress %}
            {% compress js %}
            <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
            <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
            <!--[if lt IE 9]>
                <script src="{% static "blog/js/html5shiv.js" %}"></script>
                <script src="{% static "blog/js/respond.min.js" %}"></script>
            <![endif]-->
            {% endcompress %}

            </head>
        <body>
        
            <!-- Navigation -->
            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                <div class="container">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="{% url 'blog.views.index' %}">Know Arbitrage</a>
                    </div>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            {% for page in pages%}
                            <li>
                                <a href="{{page.get_absolute_url}}">{{page.title}}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <!-- /.navbar-collapse -->
                </div>
                <!-- /.container -->
            </nav>
            <!-- Page Content -->
            <div class="container">
        
                <div class="row">
        
                    <!-- Blog Entries Column -->
                    <div class="col-md-8">
                        {% block content %}
                        {% endblock %}
                    </div>
        
                    <!-- Blog Sidebar Widgets Column -->
                    <div class="col-md-4">
        
                        <!-- Blog Search Well -->
                        <div class="well">
                            <h4>Search Posts</h4>
                            <div class="input-group">
                                <input type="text" class="form-control">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <span class="glyphicon glyphicon-search"></span>
                                </button>
                                </span>
                            </div>
                            <!-- /.input-group -->
                        </div>
                        {% for tag in tags %}
                            {% if forloop.first %}
                            <!-- Blog Categories Well -->
                            <div class="well">
                                <h4>Post Categories</h4>
                                <div class="row">
                                    <div class="col-lg-6">
                                        <ul class="list-unstyled">
                            {% endif %}
                                            <li><a href="{% url 'blog.views.index' %}?tag={{tag.slug}}">{{tag.name}}</a>
                                            </li>
                                {% if forloop.counter|divisibleby:half_tags %}
                                        </ul>
                                    </div>
                                    <div class="col-lg-6">
                                        <ul class="list-unstyled">
                                {% endif %}
                            {% if forloop.last %}
                                        </ul>
                                    </div>
                                </div>
                                <!-- /.row -->
                            </div>
                            {% endif %}
                        {% endfor %}
                        {% if posts and stockLen > 0 %}
                        <!-- Side Widget Well -->
                        <div class="well">
                            <h4>Relevant Quotes</h4>
                        <!-- Start of Yahoo! Finance code -->
                            <iframe allowtransparency="true" marginwidth="0" marginheight="0" hspace="0" vspace="0" frameborder="0" scrolling="no"
                                    width="100%"
                                    src="http://badge.finance.yahoo.com/instrument/1.0/{% for post in posts %}{% for stock in post.stocks %}{{stock.symbol}},{% endfor %}{% endfor %}/badge;quote/HTML?AppID=vpPzT1b0oGUaGi7_AxID9gRdNAo_AA0-&sig=cz59BlEOYKnCI76TDO_qqV_V7Fg-&t=1436472604923"
                                    style="height:calc(170px + 30px * {{ stockLen }});">
                                <a href="http://finance.yahoo.com">Yahoo! Finance</a>
                            </iframe>
                        <!-- End of Yahoo! Finance code -->
                        </div>
                        {% endif %}
                        {% if post and stockLen > 0%}
                        <!-- Side Widget Well -->
                        <div class="well">
                            <h4>Relevant Quotes</h4>
                        <!-- Start of Yahoo! Finance code -->
                            <iframe allowtransparency="true" marginwidth="0" marginheight="0" hspace="0" vspace="0" frameborder="0" scrolling="no"
                                    width="100%"
                                    src="http://badge.finance.yahoo.com/instrument/1.0/{% for stock in post.stocks %}{{stock.symbol}},{% endfor %}/badge;quote/HTML?AppID=vpPzT1b0oGUaGi7_AxID9gRdNAo_AA0-&sig=cz59BlEOYKnCI76TDO_qqV_V7Fg-&t=1436472604923"
                                    style="height:calc(170px + 30px * {{ stockLen }});">
                                <a href="http://finance.yahoo.com">Yahoo! Finance</a>
                            </iframe>
                        <!-- End of Yahoo! Finance code -->
                        </div>
                        {% endif %}
        
                    </div>
        
                </div>
                <!-- /.row -->
        
                <hr>
        
                <!-- Footer -->
                <footer>
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                                <ul class="list-inline text-center">
                                    <li>
                                        <a href="https://twitter.com/knowarbitrage" target="_blank">
                                            <span class="fa-stack fa-lg">
                                                <i class="fa fa-circle fa-stack-2x"></i>
                                                <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" id="mailto">
                                            <span class="fa-stack fa-lg">
                                                <i class="fa fa-circle fa-stack-2x"></i>
                                                <i class="fa fa-envelope fa-stack-1x fa-inverse"></i>
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="https://github.com/akmiller01/" target="_blank">
                                            <span class="fa-stack fa-lg">
                                                <i class="fa fa-circle fa-stack-2x"></i>
                                                <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                            </span>
                                        </a>
                                    </li>
                                </ul>
                                <p class="copyright text-muted">Copyright &copy; Alex Miller 2015</p>
                            </div>
                        </div>
                    </div>
                </footer>
        
            </div>
            <!-- /.container -->
            <!-- jQuery -->
            {% compress js %}
            <script src="{% static "blog/js/jquery.js" %}"></script>
            <script>
                $("#mailto").click( function(e) {
                    e.preventDefault();
                    var a = "knowarbitrage", 
                          b = "gmail";
                
                    window.open("mailto:" + a + "@" + b + ".com");
                } );
                $('.input-group input').keyup(function (e) {
                    if (e.keyCode == 13) {
                        location.href = "{% url 'blog.views.index' %}?q="+encodeURI($($('.input-group input')[0]).val())
                    };
                });
                $('.input-group button').click(function (e) {
                    location.href = "{% url 'blog.views.index' %}?q="+encodeURI($($('.input-group input')[0]).val())
                });
            </script>
        
            <!-- Bootstrap Core JavaScript -->
            <script src="{% static "blog/js/bootstrap.min.js" %}"></script>

            <!--Google Analytics-->
            <script>
                /*(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
                })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
              
                ga('create', 'UA-64579799-1', 'auto');
                ga('send', 'pageview');*/
            </script>
            {% endcompress %}

        </body>
    </html>

ka/ka/templates/blog/index.html
{% extends 'blog/base.html' %}

    {% block title %} Know Arbitrage {% endblock %}
    {% load staticfiles %}
    {% block content %}
    <!-- Header -->
    <h1 class="page-header">
        Know Arbitrage <br/>
        <small>Because someone has to bring the market into equilibrium</small>
    </h1>
    
    {% for post in posts %}
    <!-- Blog Post -->
    <h2>
        <a href="{{post.get_absolute_url}}">{{post.title}}</a>
    </h2>
    <p class="lead">
        by {{post.author.get_full_name}}
    </p>
    <p><span class="glyphicon glyphicon-time"></span> Posted on
    <time datetime="{{post.created|date:"c"}}">
        {{post.created|date}} at {{post.created|date:'g:i A'}}
    </time>
    </p>
    {% if post.imageURL %}
    <hr>
    <img class="img-responsive" src={{post.imageURL}} alt={{post.title}}>
    <hr>
    {% endif %}
    <p>{{post.description}}</p>
    <a class="btn btn-primary" href="{{post.get_absolute_url}}">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>

    <hr>
    {% endfor %}

    <!-- Pager -->
    <ul class="pager">
        {% if posts.has_next %}
            <li class="next">
                {% if tagParam %}
                <a href="?page={{ posts.next_page_number }}&tag={{tagParam}}">Older &rarr;</a>
                {% elif queryParam %}
                <a href="?page={{ posts.next_page_number }}&q={{queryParam}}">Older &rarr;</a>
                {% else %}
                <a href="?page={{ posts.next_page_number }}">Older &rarr;</a>
                {% endif %}
            </li>
        {% endif %}
        {% if posts.has_previous %}
            <li class="previous">
                {% if tagParam %}
                <a href="?page={{ posts.previous_page_number }}&tag={{tagParam}}">&larr; Newer</a>
                {% elif queryParam %}
                <a href="?page={{ posts.previous_page_number }}&q={{queryParam}}">&larr; Newer</a>
                {% else %}
                <a href="?page={{ posts.previous_page_number }}">&larr; Newer</a>
                {% endif %}
            </li>
        {% endif %}
    </ul>
    {% endblock %}

ka/ka/templates/blog/page.html
{% extends 'blog/base.html' %}

    {% block title %} {{page.title}} {% endblock %}
    {% load staticfiles %}
    {% block content %}
    <!-- Header -->
    <h1 class="page-header">
        {{page.title}} <br/>
        <small>{{page.subtitle}}</small>
    </h1>
    
    {{page.content|safe}}
    
    {% endblock %}

ka/ka/templates/blog/post.html
{% extends 'blog/base.html' %}

    {% block title %} {{post.title}} {% endblock %}
    {% load staticfiles %}
    {% block content %}
    <!-- Blog Post -->

    <!-- Title -->
    <h1>{{post.title}}</h1>

    <!-- Author -->
    <p class="lead">
        by {{post.author.get_full_name}}
    </p>

    <hr>

    <!-- Date/Time -->
    <p><span class="glyphicon glyphicon-time"></span>
    <time datetime="{{post.created|date:"c"}}">
        {{post.created|date}} at {{post.created|date:'g:i A'}}
    </time>
    </p>

    <!-- Preview Image -->
    {% if post.imageURL %}
    <hr>
    <img class="img-responsive" src={{post.imageURL}} alt={{post.title}}>
    {% endif %}

    <hr>

    <!-- Post Content -->
    {{post.content|safe}}
    <hr>

    <!-- Blog Comments -->

    <!-- Comments Form -->
    <div class="well">
        <h4>Leave a Comment:</h4>
        <form role="form" action="{{post.get_comment_url}}" method="POST">{% csrf_token %}
            <div class="form-group">
                <label for="id_author">Name</label>
                {{ form.author }}
            </div>
            <div class="form-group">
                <label for="id_body">Comment</label>
                {{ form.body }}
            </div>
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="message {{ message.tags }}"{% endif %}>
                    {{ message }}
                </li>
                {% endfor %}
            </ul>
            {% endif %}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

    <hr>

    <!-- Posted Comments -->

    <!-- Comment -->
    {% for comment in comments%}
    <div class="media{% if comment.admin %} admin-comment{% endif %}">
        <div class="media-body">
            <h4 class="media-heading">
                {% if comment.admin %}<span class="glyphicon glyphicon-star"></span>{% endif %}
                {{comment.author}}
                <small>
                    <time datetime="{{comment.created|date:"c"}}">
                        {{comment.created|date}} at {{comment.created|date:'g:i A'}}
                    </time>
                </small>
            </h4>
            {{comment.body}}
        </div>
    </div>
    {% empty %}
    <div class="media">
        <div class="media-body">
            <h4 class="media-heading">No comments, yet. Why not add one yourself?
            </h4>
        </div>
    </div>
    {% endfor %}
    {% endblock %}